### PR TITLE
remove python and update go client

### PR DESCRIPTION
**Pull request by skhalsa-sigsci**

### CODE REVIEW

**Comment by dkegel-fastly** [comment]
looks awesome but I think this PR should also update README.md to have the new usage instructions.

Also, consider using the tools package convention to pin a particular version of nuclei; see e.g. https://play-with-go.dev/tools-as-dependencies_go119_en

**Comment by skhalsa-sigsci** [comment]
good catch forgot to save and commit the readme

**Comment by dkegel-fastly** [comment]
btw using a pinned version of nuclei would be the next best thing to using its go api.  Users would not need to install nuclei!

**Comment by skhalsa-sigsci** [comment]
> btw using a pinned version of nuclei would be the next best thing to using its go api. Users would not need to install nuclei!

good idea. I think direct integration will take some more time to look into. Feel free to open separate PR.

**Review by dkegel-fastly — DISMISSED** [review]
LGTM

**Review by k0pak4 — DISMISSED** [review]

**Comment by skhalsa-sigsci** [comment]
made a couple corrections in the readme, should be gtg now.

**Review by dkegel-fastly — APPROVED** [review]
LEBTM

**Pull request merged**
